/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import conexiones.*; 
import farmatec.*; 
import static conexiones.conexion.Consulta;
import java.io.*;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.itextpdf.text.DocumentException; //se encarga de capturar los posibles errores..
import com.itextpdf.text.pdf.PdfPTable; //contiene el codigo necesario para tabular un archivo PDF
import com.itextpdf.text.pdf.PdfWriter; // //contiene el codigo necesario para crear un archivo PDF
import java.awt.HeadlessException;
import java.util.Random;
import java.awt.print.PrinterException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author mac
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    static ResultSet res;

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }

   
     /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFechaInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFechaFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTipoPedido = new javax.swing.JComboBox();
        jButtonMontoRecau = new javax.swing.JButton();
        jButtonMontoRecauTipoPedido = new javax.swing.JButton();
        jButtonMejoresClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox();
        jLabelMontoRecaudado = new javax.swing.JLabel();
        jLabelMontoRecaudadoPorPedido = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableListaPedidos1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldIDOrder = new javax.swing.JTextField();
        jTextFieldClientID = new javax.swing.JTextField();
        jTextFieldPharmacy = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetallePedido = new javax.swing.JTextArea();
        jTextFieldFIMES3 = new javax.swing.JTextField();
        jTextFieldFIDIA2 = new javax.swing.JTextField();
        jTextFieldFIANIO3 = new javax.swing.JTextField();
        jTextFieldEstadoPedido = new javax.swing.JTextField();
        jTextFieldTipoPedido = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBoxEscogerSucursal = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jButtonDineroRecaudado = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabelMontoRecaudadoAdmi2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListaPedidos = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jLabelMontoRecaudadoAdmi3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButtonMontopedidos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCantidadPedidosFecha = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jComboBoxTipoOrden = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMontoPedidos = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jTextFieldFIMES = new javax.swing.JTextField();
        jTextFieldFIDIA = new javax.swing.JTextField();
        jTextFieldFIANIO = new javax.swing.JTextField();
        jTextFieldFFANIO = new javax.swing.JTextField();
        jTextFieldFFDIA = new javax.swing.JTextField();
        jTextFieldFFMES = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextFieldFIMES1 = new javax.swing.JTextField();
        jTextFieldFIDIA1 = new javax.swing.JTextField();
        jTextFieldFIANIO1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldFFMES1 = new javax.swing.JTextField();
        jTextFieldFFDIA1 = new javax.swing.JTextField();
        jTextFieldFFANIO1 = new javax.swing.JTextField();
        jTextFieldFIMES2 = new javax.swing.JTextField();
        jTextFieldFIANIO2 = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setText("Consultas gerente");

        jLabel3.setText("Fecha inicial");

        jLabel4.setText("Fecha final");

        jTextFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaFinalActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo pedido");

        jComboBoxTipoPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Special" }));
        jComboBoxTipoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPedidoActionPerformed(evt);
            }
        });

        jButtonMontoRecau.setText("Consultar monto recaudado");
        jButtonMontoRecau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMontoRecauActionPerformed(evt);
            }
        });

        jButtonMontoRecauTipoPedido.setText("Consultar monto recaudado según tipo de pedido");

        jButtonMejoresClientes.setText("Tres mejores clientes");

        jLabel1.setText("Sucursal");

        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San Jose", "Cartago", "Heredia" }));

        jLabelMontoRecaudado.setText("0");

        jLabelMontoRecaudadoPorPedido.setText("0");

        jTableListaPedidos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Apellido"
            }
        ));
        jScrollPane6.setViewportView(jTableListaPedidos1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMejoresClientes)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonMontoRecauTipoPedido)
                                .addGap(46, 46, 46)
                                .addComponent(jLabelMontoRecaudadoPorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonMontoRecau)
                                .addGap(39, 39, 39)
                                .addComponent(jLabelMontoRecaudado))
                            .addComponent(jLabel2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, 91, Short.MAX_VALUE)
                                        .addComponent(jComboBoxTipoPedido, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMontoRecau)
                    .addComponent(jLabelMontoRecaudado))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMontoRecauTipoPedido)
                    .addComponent(jLabelMontoRecaudadoPorPedido))
                .addGap(18, 18, 18)
                .addComponent(jButtonMejoresClientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Módulo Gerente", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Registro de pedidos");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ingrese sus datos para realizar el pedido");

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID Orden");

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Fecha");

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cedula Cliente");

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Estado pedido");

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tipo de orden");

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Detalle");

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ID Pharmacy ");

        jButton7.setText("Ingresar Pedido");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextAreaDetallePedido.setColumns(20);
        jTextAreaDetallePedido.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetallePedido);

        jTextFieldFIMES3.setText("10");
        jTextFieldFIMES3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIMES3ActionPerformed(evt);
            }
        });

        jTextFieldFIDIA2.setText("01");
        jTextFieldFIDIA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIDIA2ActionPerformed(evt);
            }
        });

        jTextFieldFIANIO3.setText("2020");
        jTextFieldFIANIO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIANIO3ActionPerformed(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Delivered = 1, Ready to deliver =0");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Special = 1, Regular=0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel25))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldIDOrder)
                                .addComponent(jTextFieldClientID)
                                .addComponent(jTextFieldPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldFIMES3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFIDIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFIANIO3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(567, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 300, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel22))
                    .addComponent(jTextFieldIDOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldFIMES3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFIDIA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFIANIO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jTextFieldTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextFieldPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jButton7)))
                .addGap(40, 164, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Módulo Clientes", jPanel3);

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Cantidad de dinero recaudado");

        jComboBoxEscogerSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Cartago", "Heredia" }));
        jComboBoxEscogerSucursal.setToolTipText("");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Sucursal");

        jButtonDineroRecaudado.setText("Consultar");
        jButtonDineroRecaudado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDineroRecaudadoActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Total:");

        jLabelMontoRecaudadoAdmi2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMontoRecaudadoAdmi2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMontoRecaudadoAdmi2.setText("0");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Cantidad de pedidos según cliente para un rango de fechas específico");

        jLabel39.setForeground(new java.awt.Color(240, 240, 240));
        jLabel39.setText("Fecha Inicio");

        jLabel40.setForeground(new java.awt.Color(240, 240, 240));
        jLabel40.setText("Fecha final");

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTableListaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "ID Orden "
            }
        ));
        jScrollPane3.setViewportView(jTableListaPedidos);
        if (jTableListaPedidos.getColumnModel().getColumnCount() > 0) {
            jTableListaPedidos.getColumnModel().getColumn(2).setHeaderValue("ID Orden ");
        }

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Total:");

        jLabelMontoRecaudadoAdmi3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMontoRecaudadoAdmi3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMontoRecaudadoAdmi3.setText("0");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Monto de pedidos según cliente para un rango de fechas específico");

        jButtonMontopedidos.setText("Consultar");
        jButtonMontopedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMontopedidosActionPerformed(evt);
            }
        });

        jTableCantidadPedidosFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Orden", "Monto"
            }
        ));
        jScrollPane4.setViewportView(jTableCantidadPedidosFecha);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Listado de pedidos de un tipo en un mes en especifico");

        jLabel46.setForeground(new java.awt.Color(240, 240, 240));
        jLabel46.setText("Mes y año a Consultar");

        jComboBoxTipoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Special" }));
        jComboBoxTipoOrden.setToolTipText("");

        jLabel48.setForeground(new java.awt.Color(240, 240, 240));
        jLabel48.setText("Tipo de pedido");

        jTableMontoPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Monto del pedido "
            }
        ));
        jScrollPane5.setViewportView(jTableMontoPedidos);

        jButton8.setText("Consultar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextFieldFIMES.setText("10");
        jTextFieldFIMES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIMESActionPerformed(evt);
            }
        });

        jTextFieldFIDIA.setText("01");
        jTextFieldFIDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIDIAActionPerformed(evt);
            }
        });

        jTextFieldFIANIO.setText("2018");
        jTextFieldFIANIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIANIOActionPerformed(evt);
            }
        });

        jTextFieldFFANIO.setText("2025");
        jTextFieldFFANIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFANIOActionPerformed(evt);
            }
        });

        jTextFieldFFDIA.setText("23");
        jTextFieldFFDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFDIAActionPerformed(evt);
            }
        });

        jTextFieldFFMES.setText("06");
        jTextFieldFFMES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFMESActionPerformed(evt);
            }
        });

        jLabel47.setForeground(new java.awt.Color(240, 240, 240));
        jLabel47.setText("Fecha Inicio");

        jTextFieldFIMES1.setText("05");
        jTextFieldFIMES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIMES1ActionPerformed(evt);
            }
        });

        jTextFieldFIDIA1.setText("22");
        jTextFieldFIDIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIDIA1ActionPerformed(evt);
            }
        });

        jTextFieldFIANIO1.setText("2015");
        jTextFieldFIANIO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIANIO1ActionPerformed(evt);
            }
        });

        jLabel49.setForeground(new java.awt.Color(240, 240, 240));
        jLabel49.setText("Fecha final");

        jTextFieldFFMES1.setText("12");
        jTextFieldFFMES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFMES1ActionPerformed(evt);
            }
        });

        jTextFieldFFDIA1.setText("17");
        jTextFieldFFDIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFDIA1ActionPerformed(evt);
            }
        });

        jTextFieldFFANIO1.setText("2020");
        jTextFieldFFANIO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFFANIO1ActionPerformed(evt);
            }
        });

        jTextFieldFIMES2.setText("08");
        jTextFieldFIMES2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIMES2ActionPerformed(evt);
            }
        });

        jTextFieldFIANIO2.setText("2019");
        jTextFieldFIANIO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFIANIO2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel46)
                            .addGap(30, 30, 30)
                            .addComponent(jTextFieldFIMES2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldFIANIO2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxTipoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41)
                                .addComponent(jLabelMontoRecaudadoAdmi3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel37)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFIMES1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFIDIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFIANIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFFMES1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFFDIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFFANIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMontopedidos)))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMontoRecaudadoAdmi2)
                            .addComponent(jLabel35))
                        .addGap(48, 48, 48)
                        .addComponent(jButtonDineroRecaudado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addGap(66, 66, 66)
                        .addComponent(jComboBoxEscogerSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel42))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFIMES, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFIDIA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFIANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFFMES, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFFDIA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFFANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(jComboBoxEscogerSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(jButtonDineroRecaudado))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabelMontoRecaudadoAdmi2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jTextFieldFIMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFIDIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFIANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jTextFieldFFMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFFDIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFFANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMontoRecaudadoAdmi3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMontopedidos)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jTextFieldFIMES1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFIDIA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFIANIO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFFMES1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFFDIA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFFANIO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(jTextFieldFIMES2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFIANIO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)))
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modulo Administrador", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPedidoActionPerformed

    private void jButtonMontoRecauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMontoRecauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMontoRecauActionPerformed

    private void jTextFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaFinalActionPerformed
public void CargarMontoTotal() {
         String Sucursal = (jComboBoxEscogerSucursal.getSelectedItem().toString() );
        String Consulta ;
        switch (Sucursal){
            case "Heredia":
                Consulta = "select sum (totalAmount) from client_orderHeredia";
                res =conexiones.conexion.Consulta(Consulta);
                try {
                    while (res.next()){
                         jLabelMontoRecaudadoAdmi2.setText(""+res.getString("sum (totalAmount)")+"");
                     }
                }   
                     catch (Exception e) {
                        }
                break;
            case "San José":
                Consulta = "select sum (totalAmount) from client_orderSanJose";
                res =conexiones.conexion.Consulta(Consulta);
                    jLabelMontoRecaudadoAdmi2.setText(""+res+"");
           
                break;
            case "Cartago":
                Consulta = "select sum (totalAmount) from client_orderCartago";
                res =conexiones.conexion.Consulta(Consulta);
                try {
                    while (res.next()){
                         jLabelMontoRecaudadoAdmi2.setText(""+res.getString("totalAmount")+"");
                     }
                }   
                     catch (Exception e) {
                        }
                break;
        }
        
     }
    private void jButtonDineroRecaudadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDineroRecaudadoActionPerformed
        CargarMontoTotal() ;
  
    }//GEN-LAST:event_jButtonDineroRecaudadoActionPerformed
public int contar_num_ordenes(){ 
     int n= 0;
     String fechaInicio = jTextFieldFIMES.getText() + "/" + jTextFieldFIDIA.getText() + "/" + jTextFieldFIANIO.getText();
     String fecha_final = jTextFieldFFMES.getText() + "/" + jTextFieldFFDIA.getText() + "/" + jTextFieldFFANIO.getText();  
          
        res =conexiones.conexion.Consulta("select COUNT (idOrder )from client join client_order on client.idClient = client_order.idClient where "
                   + "orderDate between '"+fechaInicio+"' and '"+fecha_final+"'" ); 
     

        try {
            // chequeo que el result set no sea vacío, moviendo el cursor a la
            // primer fila. (El cursor inicia antes de la primer fila)
            if(res.next()) {
                //Si hay resultados obtengo el valor.
                n= res.getInt(1);
            }  } catch (SQLException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
  
     return n;
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    cargarListadoClientes();
    jLabelMontoRecaudadoAdmi3.setText(""+contar_num_ordenes()+"");
     
      //     jLabelMontoRecaudadoAdmi3.setText(""+res.getInt("idOrder")+"");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldFIMESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIMESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIMESActionPerformed
public void CargarListadoTipoMes () {
               DefaultTableModel modelo = (DefaultTableModel) jTableCantidadPedidosFecha.getModel();
               modelo.setRowCount(0);
               String fechaInicio3 = jTextFieldFIMES2.getText() + "/" + 01 + "/" + jTextFieldFIANIO2.getText();
            String fecha_final3 = jTextFieldFIMES2.getText() + "/" +30 + "/" + jTextFieldFIANIO2.getText();  
        
           res =conexiones.conexion.Consulta ("select client_order.idOrder, price from client_order join orderDrug on client_order.idOrder= orderDrug.idOrder "
                   + "inner join  drugs on orderDrug.idDrug= drugs.idDrug inner join order_type on client_order.idOrderType ="
                   + "order_type.idOrderType where order_type.orderDetail ='"+jComboBoxTipoOrden.getSelectedItem().toString()+"'"
                           + " and orderDate between  '"+fechaInicio3+"' and '"+fecha_final3+"'");  
           try {
               while (res.next()){
                     Vector vec = new Vector();
                     vec.add(res.getInt(1));
                     vec.add(res.getInt(2));
                     modelo.addRow(vec);
                     jTableCantidadPedidosFecha.setModel(modelo);
                }
           }   
                catch (Exception e) {
                }
        }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// ESTA ES LA CONSULTA SQL QUE FUNCIONA EN SU TOTALIDAD
//select client_order.idOrder, price from client_order join orderDrug on client_order.idOrder= orderDrug.idOrder 
//	inner join  drugs on orderDrug.idDrug= drugs.idDrug inner join order_type on client_order.idOrderType = 
//		order_type.idOrderType where order_type.orderDetail = 'Regular'        // TODO add your handling code here:

CargarListadoTipoMes () ;
//Falta el filtro por fecha
    }//GEN-LAST:event_jButton8ActionPerformed
    private void CargarListadoPeriodoMonto () {
         DefaultTableModel modelo = (DefaultTableModel) jTableMontoPedidos.getModel();
               modelo.setRowCount(0);
           //    Date fechaInicio =  (jDateChooserFIR2.getDate());
            //   Date fecha_final =  (jDateChooserFFR2 .getDate());
            String fechaInicio2 = jTextFieldFIMES1.getText() + "/" + jTextFieldFIDIA1.getText() + "/" + jTextFieldFIANIO1.getText();
            String fecha_final2 = jTextFieldFFMES1.getText() + "/" + jTextFieldFFDIA1.getText() + "/" + jTextFieldFFANIO1.getText();  
        
           res =conexiones.conexion.Consulta("select firstName, lastName, price from client join client_order on client_order.idClient= client.idClient"
                   + " inner join orderDrug on client_order.idOrder= orderDrug.idOrder inner join drugs on orderDrug.idDrug= "
                   + " drugs.idDrug where orderDate between  '"+fechaInicio2+"' and '"+fecha_final2+"'");
           try {
               while (res.next()){
                     Vector vec = new Vector();
                     vec.add(res.getString(1));
                     vec.add(res.getString(2));
                     vec.add(res.getInt(3));
                     modelo.addRow(vec);
                     jTableMontoPedidos.setModel(modelo);
                }
           }   
                catch (Exception e) {
                }
    } 

    private void jButtonMontopedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMontopedidosActionPerformed
       // ESTA ES LA CONSULTA SQL QUE FUNCIONA EN SU TOTALIDAD
        //    select firstName, lastName, price from client join client_order on client_order.idClient= client.idClient
	//	inner join orderDrug on client_order.idOrder= orderDrug.idOrder inner join drugs on orderDrug.idDrug= 
	//	drugs.idDrug where orderDate between '10/10/2000' and '10/10/2025' ;
        CargarListadoPeriodoMonto ();
    }//GEN-LAST:event_jButtonMontopedidosActionPerformed

    private void jTextFieldFIDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIDIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIDIAActionPerformed

    private void jTextFieldFIANIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIANIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIANIOActionPerformed

    private void jTextFieldFFANIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFANIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFANIOActionPerformed

    private void jTextFieldFFDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFDIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFDIAActionPerformed

    private void jTextFieldFFMESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFMESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFMESActionPerformed

    private void jTextFieldFIMES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIMES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIMES1ActionPerformed

    private void jTextFieldFIDIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIDIA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIDIA1ActionPerformed

    private void jTextFieldFIANIO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIANIO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIANIO1ActionPerformed

    private void jTextFieldFFMES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFMES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFMES1ActionPerformed

    private void jTextFieldFFDIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFDIA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFDIA1ActionPerformed

    private void jTextFieldFFANIO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFFANIO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFFANIO1ActionPerformed

    private void jTextFieldFIMES2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIMES2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIMES2ActionPerformed

    private void jTextFieldFIANIO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIANIO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIANIO2ActionPerformed

    private void jTextFieldFIMES3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIMES3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIMES3ActionPerformed

    private void jTextFieldFIDIA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIDIA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIDIA2ActionPerformed

    private void jTextFieldFIANIO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFIANIO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFIANIO3ActionPerformed
    Pedido pedido = new Pedido();
    procedimientos procedimiento= new procedimientos();
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pedido.setIdPharmacy(Integer.parseInt(jTextFieldPharmacy.getText().toString()));
        pedido.setIdOrder(Integer.parseInt(jTextFieldIDOrder.getText().toString()));
        String fechaPedido = jTextFieldFIMES3.getText() + "/" + jTextFieldFIDIA2.getText() + "/" + jTextFieldFIANIO3.getText();
        pedido.setOrderDate(fechaPedido);
        pedido.setIdClient(Integer.parseInt(jTextFieldClientID.getText().toString()));
        pedido.setIdStatus(Integer.parseInt(jTextFieldEstadoPedido.getText().toString()));
        pedido.setIdOrderType(Integer.parseInt(jTextFieldTipoPedido.getText().toString()));
        pedido.setDetail(jTextAreaDetallePedido.getText().toString());
        
        //Se hace la insercion en la tabla vehiculo en POO
        int exito = 0;
        exito= procedimiento.AgregarPedido (pedido.getIdPharmacy(), pedido.getIdOrder(), pedido.getOrderDate(),
                pedido.getIdClient(),pedido.getIdStatus(), pedido.getIdOrderType(), pedido.getDetail());
        if(exito>0){
            JOptionPane.showMessageDialog(null, "Los datos se han guardado correctamente",
                    "Éxito en la operación", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Los datos no se pudieron guardar\n"
                    + "Inténtelo nuevamente", "Error en la operación", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonDineroRecaudado;
    private javax.swing.JButton jButtonMejoresClientes;
    private javax.swing.JButton jButtonMontoRecau;
    private javax.swing.JButton jButtonMontoRecauTipoPedido;
    private javax.swing.JButton jButtonMontopedidos;
    private javax.swing.JComboBox<String> jComboBoxEscogerSucursal;
    private javax.swing.JComboBox jComboBoxSucursal;
    private javax.swing.JComboBox<String> jComboBoxTipoOrden;
    private javax.swing.JComboBox jComboBoxTipoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMontoRecaudado;
    private javax.swing.JLabel jLabelMontoRecaudadoAdmi2;
    private javax.swing.JLabel jLabelMontoRecaudadoAdmi3;
    private javax.swing.JLabel jLabelMontoRecaudadoPorPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableCantidadPedidosFecha;
    private javax.swing.JTable jTableListaPedidos;
    private javax.swing.JTable jTableListaPedidos1;
    private javax.swing.JTable jTableMontoPedidos;
    private javax.swing.JTextArea jTextAreaDetallePedido;
    private javax.swing.JTextField jTextFechaFinal;
    private javax.swing.JTextField jTextFechaInicial;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldClientID;
    private javax.swing.JTextField jTextFieldEstadoPedido;
    private javax.swing.JTextField jTextFieldFFANIO;
    private javax.swing.JTextField jTextFieldFFANIO1;
    private javax.swing.JTextField jTextFieldFFDIA;
    private javax.swing.JTextField jTextFieldFFDIA1;
    private javax.swing.JTextField jTextFieldFFMES;
    private javax.swing.JTextField jTextFieldFFMES1;
    private javax.swing.JTextField jTextFieldFIANIO;
    private javax.swing.JTextField jTextFieldFIANIO1;
    private javax.swing.JTextField jTextFieldFIANIO2;
    private javax.swing.JTextField jTextFieldFIANIO3;
    private javax.swing.JTextField jTextFieldFIDIA;
    private javax.swing.JTextField jTextFieldFIDIA1;
    private javax.swing.JTextField jTextFieldFIDIA2;
    private javax.swing.JTextField jTextFieldFIMES;
    private javax.swing.JTextField jTextFieldFIMES1;
    private javax.swing.JTextField jTextFieldFIMES2;
    private javax.swing.JTextField jTextFieldFIMES3;
    private javax.swing.JTextField jTextFieldIDOrder;
    private javax.swing.JTextField jTextFieldPharmacy;
    private javax.swing.JTextField jTextFieldTipoPedido;
    // End of variables declaration//GEN-END:variables

 
          
    private void cargarListadoClientes() {
         DefaultTableModel modelo = (DefaultTableModel) jTableListaPedidos.getModel();
               modelo.setRowCount(0);
           //    Date fechaInicio =  (jDateChooserFIR2.getDate());
            //   Date fecha_final =  (jDateChooserFFR2 .getDate());
            String fechaInicio = jTextFieldFIMES.getText() + "/" + jTextFieldFIDIA.getText() + "/" + jTextFieldFIANIO.getText();
            String fecha_final = jTextFieldFFMES.getText() + "/" + jTextFieldFFDIA.getText() + "/" + jTextFieldFFANIO.getText();  
          
           res =conexiones.conexion.Consulta("select firstName, lastName, idOrder from client join client_order on client.idClient = client_order.idClient where "
                   + "orderDate between '"+fechaInicio+"' and '"+fecha_final+"'" ); 
           try {
               while (res.next()){
                     Vector vec = new Vector();
                     vec.add(res.getString(1));
                     vec.add(res.getString(2));
                     vec.add(res.getInt(3));
                     modelo.addRow(vec);
                     jTableListaPedidos.setModel(modelo);
                }
           }   
                catch (Exception e) {
                }
    }
}
